/**
 * TypeSafe (System One / Jev) triage for one email. Code owns the workflow; the model answers a few
 * narrow typed questions over metadata only (sender, subject, snippet, list headers). Bodies are never sent.
 */
import { choice, noul } from "@typesafe-ai/sdk";
import { jev } from "@/lib/ai/client";
import { CATEGORIES, type CategoryId } from "@/lib/policy/schema";
import type { Judgment } from "@/db/schema";
import type { GmailMessageMeta } from "@/lib/gmail/client";

// Price from https://docs.typesafe.ai/models: $0.042 per million input tokens; output tokens are free.
export const USD_PER_INPUT_TOKEN = 0.042 / 1_000_000;

/** What the thread around a message says about who spoke last. */
export type ThreadFacts = { total: number; lastFromMe: boolean; repliedAfterLatest: boolean; lastInboundAt: string | null };

const categoryCriteria = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, c.description]),
) as Record<CategoryId, string>;

export function messageState(meta: GmailMessageMeta, userEmail: string, thread?: ThreadFacts) {
  const h = meta.headers;
  return {
    recipient: userEmail,
    from: h["from"] ?? "",
    to: h["to"] ?? "",
    cc: h["cc"] ?? null,
    subject: h["subject"] ?? "",
    date: h["date"] ?? "",
    is_reply: Boolean(h["in-reply-to"]) || /^\s*re:/i.test(h["subject"] ?? ""),
    status: { recipient_has_read_it: !meta.labelIds.includes("UNREAD"), starred: meta.labelIds.includes("STARRED"), in_inbox: meta.labelIds.includes("INBOX") },
    thread: thread ? { messages: thread.total, last_message_from: thread.lastFromMe ? "recipient" : "other party", recipient_replied_after_this: thread.repliedAfterLatest } : null,
    preview: meta.snippet.slice(0, 600),
    bulk_headers: {
      has_list_unsubscribe: Boolean(h["list-unsubscribe"]),
      precedence: h["precedence"] ?? null,
      auto_submitted: h["auto-submitted"] ?? null,
    },
    gmail_tab: meta.labelIds.find((l) => l.startsWith("CATEGORY_"))?.replace("CATEGORY_", "").toLowerCase() ?? null,
  };
}

export const QUESTIONS = {
  category: choice(
    {
      question: "Which mailbox category best fits this email? Judge from the sender, subject, preview, and bulk-mail headers.",
      note: "Automated mail from a company the recipient works at is still `work`. Mail written personally by a human at a company is `work`, not marketing. Pick `other` when nothing fits or the evidence is too thin.",
    },
    categoryCriteria,
  ),
  automated: noul(
    "Was this email generated by a system or bulk mailer rather than written by a person for this specific recipient?",
    { true: "Bulk campaign, notification, digest, receipt, or no-reply system mail.", false: "A person wrote this message to the recipient, even if briefly." },
  ),
  needs_action: noul(
    { question: "Does the recipient still need to do something because of this email: reply, decide, pay, sign, schedule, or respond by a deadline?", note: "When `thread.recipient_replied_after_this` is true the recipient has already answered; only a new ask in the preview would still need action." },
    { true: "A concrete action or reply is still expected from the recipient.", false: "Purely informational, promotional, already handled, or already answered; nothing is asked of the recipient." },
  ),
  time_sensitive: noul(
    "Does this email lose its value if not seen within a few days?",
    { true: "A code, deadline, delivery window, event date, or expiring offer within days.", false: "No time pressure; equally useful next month." },
  ),
  disposable: noul(
    "Once the recipient has seen this email, would nothing be lost by trashing it?",
    { true: "Promotion, notification, digest, expired code, or duplicate of something the recipient has elsewhere.", false: "A record, receipt, statement, ticket, personal message, or anything someone might search for later." },
  ),
} as const;

export type TriageResult = { judgment: Judgment; model: string; inputTokens: number; outputTokens: number };

export async function triageMessage(meta: GmailMessageMeta, userEmail: string, thread?: ThreadFacts): Promise<TriageResult> {
  const res = await jev().systemOne({ state: messageState(meta, userEmail, thread), questions: QUESTIONS });
  const cat = res.answers.category;
  return {
    judgment: {
      category: cat.choice,
      categoryConfidence: cat.confidence,
      probabilities: cat.probabilities as Record<string, number>,
      automated: res.answers.automated.noul,
      needsAction: res.answers.needs_action.noul,
      timeSensitive: res.answers.time_sensitive.noul,
      disposable: res.answers.disposable.noul,
      ...(thread ? { repliedAfter: thread.repliedAfterLatest, threadMessages: thread.total } : {}),
    },
    model: res.model,
    inputTokens: res.usage.input_tokens,
    outputTokens: res.usage.output_tokens,
  };
}

/** Rough per-message token estimate for budget checks before a run (state + four questions). */
export const ESTIMATED_TOKENS_PER_MESSAGE = 1300; // measured on 2026-09-25: 1,188 to 1,224 tokens per message with four questions
export function estimateCostUsd(messages: number): number {
  return messages * ESTIMATED_TOKENS_PER_MESSAGE * USD_PER_INPUT_TOKEN;
}
